from setting import Setting
from protocol import aloha,slotted_aloha,csma,csma_cd
import matplotlib.pyplot as plt
import numpy as np

class every_rate:
    def __init__(self) -> None:
        self.success_rate_list = []
        self.idle_rate_list = []
        self.collision_rate_list = []


def main():

    # Q1
    # host_num_list = [2,3,4,6]
    # packet_num_list = [1200,800,600,400]
    # aloha_list = every_rate()
    # slotted_aloha_list = every_rate()
    # csma_list = every_rate()
    # csma_cd_list = every_rate()
    # for h,p in zip(host_num_list, packet_num_list):
    #     sets =  Setting(host_num=h, packet_num=p, max_colision_wait_time=20, p_resend=0.3)

    #     print(sets.host_num,sets.packet_num)
    #     success_rate, idle_rate, collision_rate = aloha(sets)
    #     aloha_list.success_rate_list.append(success_rate)
    #     aloha_list.idle_rate_list.append(idle_rate)
    #     aloha_list.collision_rate_list.append(collision_rate)
    #     print(success_rate,idle_rate,collision_rate)
    #     success_rate, idle_rate, collision_rate = slotted_aloha(sets)
    #     slotted_aloha_list.success_rate_list.append(success_rate)
    #     slotted_aloha_list.idle_rate_list.append(idle_rate)
    #     slotted_aloha_list.collision_rate_list.append(collision_rate)
    #     print(success_rate,idle_rate,collision_rate)
    #     success_rate, idle_rate, collision_rate = csma(sets)
    #     csma_list.success_rate_list.append(success_rate)
    #     csma_list.idle_rate_list.append(idle_rate)
    #     csma_list.collision_rate_list.append(collision_rate)
    #     print(success_rate,idle_rate,collision_rate)
    #     success_rate, idle_rate, collision_rate = csma_cd(sets)
    #     csma_cd_list.success_rate_list.append(success_rate)
    #     csma_cd_list.idle_rate_list.append(idle_rate)
    #     csma_cd_list.collision_rate_list.append(collision_rate)
    #     print(success_rate,idle_rate,collision_rate)

    # plt.xlabel('Host Num')
    # plt.ylabel('Success Rate')
    # plt.plot(host_num_list,aloha_list.success_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(host_num_list,slotted_aloha_list.success_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(host_num_list,csma_list.success_rate_list,marker = '*',label = 'csma')
    # plt.plot(host_num_list,csma_cd_list.success_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # plt.xlabel('Host Num')
    # plt.ylabel('Idle Rate')
    # plt.plot(host_num_list,aloha_list.idle_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(host_num_list,slotted_aloha_list.idle_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(host_num_list,csma_list.idle_rate_list,marker = '*',label = 'csma')
    # plt.plot(host_num_list,csma_cd_list.idle_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # plt.xlabel('Host Num')
    # plt.ylabel('Collision Rate')
    # plt.plot(host_num_list,aloha_list.collision_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(host_num_list,slotted_aloha_list.collision_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(host_num_list,csma_list.collision_rate_list,marker = '*',label = 'csma')
    # plt.plot(host_num_list,csma_cd_list.collision_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # Q2

    # Q3 

    # host_num_list = [2,3,4,6]
    # packet_num_list = [1200,800,600,400]
    # aloha_list = every_rate()
    # slotted_aloha_list = every_rate()
    # csma_list = every_rate()
    # csma_cd_list = every_rate()
    # for h,p in zip(host_num_list, packet_num_list):
    #     sets =  Setting(host_num=h, packet_num=p)

    #     # print(sets.host_num,sets.packet_num)
    #     success_rate, idle_rate, collision_rate = aloha(sets)
    #     aloha_list.success_rate_list.append(success_rate)
    #     aloha_list.idle_rate_list.append(idle_rate)
    #     aloha_list.collision_rate_list.append(collision_rate)
    #     # print(success_rate,idle_rate,collision_rate)
    #     success_rate, idle_rate, collision_rate = slotted_aloha(sets)
    #     slotted_aloha_list.success_rate_list.append(success_rate)
    #     slotted_aloha_list.idle_rate_list.append(idle_rate)
    #     slotted_aloha_list.collision_rate_list.append(collision_rate)
    #     # print(success_rate,idle_rate,collision_rate)
    #     success_rate, idle_rate, collision_rate = csma(sets)
    #     csma_list.success_rate_list.append(success_rate)
    #     csma_list.idle_rate_list.append(idle_rate)
    #     csma_list.collision_rate_list.append(collision_rate)
    #     # print(success_rate,idle_rate,collision_rate)
    #     success_rate, idle_rate, collision_rate = csma_cd(sets)
    #     csma_cd_list.success_rate_list.append(success_rate)
    #     csma_cd_list.idle_rate_list.append(idle_rate)
    #     csma_cd_list.collision_rate_list.append(collision_rate)
    #     # print(success_rate,idle_rate,collision_rate)


    # plt.xlabel('Host Num')
    # plt.ylabel('Success Rate')
    # plt.plot(host_num_list,aloha_list.success_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(host_num_list,slotted_aloha_list.success_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(host_num_list,csma_list.success_rate_list,marker = '*',label = 'csma')
    # plt.plot(host_num_list,csma_cd_list.success_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # plt.xlabel('Host Num')
    # plt.ylabel('Idle Rate')
    # plt.plot(host_num_list,aloha_list.idle_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(host_num_list,slotted_aloha_list.idle_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(host_num_list,csma_list.idle_rate_list,marker = '*',label = 'csma')
    # plt.plot(host_num_list,csma_cd_list.idle_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # plt.xlabel('Host Num')
    # plt.ylabel('Collision Rate')
    # plt.plot(host_num_list,aloha_list.collision_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(host_num_list,slotted_aloha_list.collision_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(host_num_list,csma_list.collision_rate_list,marker = '*',label = 'csma')
    # plt.plot(host_num_list,csma_cd_list.collision_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # Q4

    # aloha_list = every_rate()
    # slotted_aloha_list = every_rate()
    # csma_list = every_rate()
    # csma_cd_list = every_rate()
    # for c in range(1,31):
    #     aloha_tmp = every_rate()
    #     slotted_aloha_tmp = every_rate()
    #     csma_tmp = every_rate()
    #     csma_cd_tmp = every_rate()
    #     for i in range(30):
    #         sets = Setting(coefficient=c)
    #         success_rate, idle_rate, collision_rate = aloha(sets)
    #         aloha_tmp.success_rate_list.append(success_rate)
    #         aloha_tmp.idle_rate_list.append(idle_rate)
    #         aloha_tmp.collision_rate_list.append(collision_rate)
    #         success_rate, idle_rate, collision_rate = slotted_aloha(sets)
    #         slotted_aloha_tmp.success_rate_list.append(success_rate)
    #         slotted_aloha_tmp.idle_rate_list.append(idle_rate)
    #         slotted_aloha_tmp.collision_rate_list.append(collision_rate)
    #         success_rate, idle_rate, collision_rate = csma(sets)
    #         csma_tmp.success_rate_list.append(success_rate)
    #         csma_tmp.idle_rate_list.append(idle_rate)
    #         csma_tmp.collision_rate_list.append(collision_rate)
    #         success_rate, idle_rate, collision_rate = csma_cd(sets)
    #         csma_cd_tmp.success_rate_list.append(success_rate)
    #         csma_cd_tmp.idle_rate_list.append(idle_rate)
    #         csma_cd_tmp.collision_rate_list.append(collision_rate)

    #     aloha_list.success_rate_list.append(np.mean(aloha_tmp.success_rate_list))
    #     aloha_list.collision_rate_list.append(np.mean(aloha_tmp.collision_rate_list))
    #     aloha_list.idle_rate_list.append(np.mean(aloha_tmp.idle_rate_list))
    #     slotted_aloha_list.success_rate_list.append(np.mean(slotted_aloha_tmp.success_rate_list))
    #     slotted_aloha_list.collision_rate_list.append(np.mean(slotted_aloha_tmp.collision_rate_list))
    #     slotted_aloha_list.idle_rate_list.append(np.mean(slotted_aloha_tmp.idle_rate_list))
    #     csma_list.success_rate_list.append(np.mean(csma_tmp.success_rate_list))
    #     csma_list.collision_rate_list.append(np.mean(csma_tmp.collision_rate_list))
    #     csma_list.idle_rate_list.append(np.mean(csma_tmp.idle_rate_list))
    #     csma_cd_list.success_rate_list.append(np.mean(csma_cd_tmp.success_rate_list))
    #     csma_cd_list.collision_rate_list.append(np.mean(csma_cd_tmp.collision_rate_list))
    #     csma_cd_list.idle_rate_list.append(np.mean(csma_cd_tmp.idle_rate_list))

    # plt.xlabel('Coefficient')
    # plt.ylabel('Success Rate')
    # plt.plot(range(1,31),aloha_list.success_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(range(1,31),slotted_aloha_list.success_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(range(1,31),csma_list.success_rate_list,marker = '*',label = 'csma')
    # plt.plot(range(1,31),csma_cd_list.success_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # plt.xlabel('Coefficient')
    # plt.ylabel('Idle Rate')
    # plt.plot(range(1,31),aloha_list.idle_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(range(1,31),slotted_aloha_list.idle_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(range(1,31),csma_list.idle_rate_list,marker = '*',label = 'csma')
    # plt.plot(range(1,31),csma_cd_list.idle_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # plt.xlabel('Coefficient')
    # plt.ylabel('Collision Rate')
    # plt.plot(range(1,31),aloha_list.collision_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(range(1,31),slotted_aloha_list.collision_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(range(1,31),csma_list.collision_rate_list,marker = '*',label = 'csma')
    # plt.plot(range(1,31),csma_cd_list.collision_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # Q5

    # aloha_list = every_rate()
    # slotted_aloha_list = every_rate()
    # csma_list = every_rate()
    # csma_cd_list = every_rate()
    # for p in range(100,1050,50):
    #     aloha_tmp = every_rate()
    #     slotted_aloha_tmp = every_rate()
    #     csma_tmp = every_rate()
    #     csma_cd_tmp = every_rate()
    #     for i in range(30):
    #         sets = Setting(packet_num=p)
    #         success_rate, idle_rate, collision_rate = aloha(sets)
    #         aloha_tmp.success_rate_list.append(success_rate)
    #         aloha_tmp.idle_rate_list.append(idle_rate)
    #         aloha_tmp.collision_rate_list.append(collision_rate)
    #         success_rate, idle_rate, collision_rate = slotted_aloha(sets)
    #         slotted_aloha_tmp.success_rate_list.append(success_rate)
    #         slotted_aloha_tmp.idle_rate_list.append(idle_rate)
    #         slotted_aloha_tmp.collision_rate_list.append(collision_rate)
    #         success_rate, idle_rate, collision_rate = csma(sets)
    #         csma_tmp.success_rate_list.append(success_rate)
    #         csma_tmp.idle_rate_list.append(idle_rate)
    #         csma_tmp.collision_rate_list.append(collision_rate)
    #         success_rate, idle_rate, collision_rate = csma_cd(sets)
    #         csma_cd_tmp.success_rate_list.append(success_rate)
    #         csma_cd_tmp.idle_rate_list.append(idle_rate)
    #         csma_cd_tmp.collision_rate_list.append(collision_rate)

    #     aloha_list.success_rate_list.append(np.mean(aloha_tmp.success_rate_list))
    #     aloha_list.collision_rate_list.append(np.mean(aloha_tmp.collision_rate_list))
    #     aloha_list.idle_rate_list.append(np.mean(aloha_tmp.idle_rate_list))
    #     slotted_aloha_list.success_rate_list.append(np.mean(slotted_aloha_tmp.success_rate_list))
    #     slotted_aloha_list.collision_rate_list.append(np.mean(slotted_aloha_tmp.collision_rate_list))
    #     slotted_aloha_list.idle_rate_list.append(np.mean(slotted_aloha_tmp.idle_rate_list))
    #     csma_list.success_rate_list.append(np.mean(csma_tmp.success_rate_list))
    #     csma_list.collision_rate_list.append(np.mean(csma_tmp.collision_rate_list))
    #     csma_list.idle_rate_list.append(np.mean(csma_tmp.idle_rate_list))
    #     csma_cd_list.success_rate_list.append(np.mean(csma_cd_tmp.success_rate_list))
    #     csma_cd_list.collision_rate_list.append(np.mean(csma_cd_tmp.collision_rate_list))
    #     csma_cd_list.idle_rate_list.append(np.mean(csma_cd_tmp.idle_rate_list))

    # plt.xlabel('Packet_num')
    # plt.ylabel('Success Rate')
    # plt.plot(range(100,1050,50),aloha_list.success_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(range(100,1050,50),slotted_aloha_list.success_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(range(100,1050,50),csma_list.success_rate_list,marker = '*',label = 'csma')
    # plt.plot(range(100,1050,50),csma_cd_list.success_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # plt.xlabel('Packet_num')
    # plt.ylabel('Idle Rate')
    # plt.plot(range(100,1050,50),aloha_list.idle_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(range(100,1050,50),slotted_aloha_list.idle_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(range(100,1050,50),csma_list.idle_rate_list,marker = '*',label = 'csma')
    # plt.plot(range(100,1050,50),csma_cd_list.idle_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # plt.xlabel('Packet_num')
    # plt.ylabel('Collision Rate')
    # plt.plot(range(100,1050,50),aloha_list.collision_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(range(100,1050,50),slotted_aloha_list.collision_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(range(100,1050,50),csma_list.collision_rate_list,marker = '*',label = 'csma')
    # plt.plot(range(100,1050,50),csma_cd_list.collision_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # Q6

    # aloha_list = every_rate()
    # slotted_aloha_list = every_rate()
    # csma_list = every_rate()
    # csma_cd_list = every_rate()
    # for h in range(1,11):
    #     aloha_tmp = every_rate()
    #     slotted_aloha_tmp = every_rate()
    #     csma_tmp = every_rate()
    #     csma_cd_tmp = every_rate()
    #     for i in range(30):
    #         sets = Setting(host_num=h)
    #         success_rate, idle_rate, collision_rate = aloha(sets)
    #         aloha_tmp.success_rate_list.append(success_rate)
    #         aloha_tmp.idle_rate_list.append(idle_rate)
    #         aloha_tmp.collision_rate_list.append(collision_rate)
    #         success_rate, idle_rate, collision_rate = slotted_aloha(sets)
    #         slotted_aloha_tmp.success_rate_list.append(success_rate)
    #         slotted_aloha_tmp.idle_rate_list.append(idle_rate)
    #         slotted_aloha_tmp.collision_rate_list.append(collision_rate)
    #         success_rate, idle_rate, collision_rate = csma(sets)
    #         csma_tmp.success_rate_list.append(success_rate)
    #         csma_tmp.idle_rate_list.append(idle_rate)
    #         csma_tmp.collision_rate_list.append(collision_rate)
    #         success_rate, idle_rate, collision_rate = csma_cd(sets)
    #         csma_cd_tmp.success_rate_list.append(success_rate)
    #         csma_cd_tmp.idle_rate_list.append(idle_rate)
    #         csma_cd_tmp.collision_rate_list.append(collision_rate)

    #     aloha_list.success_rate_list.append(np.mean(aloha_tmp.success_rate_list))
    #     aloha_list.collision_rate_list.append(np.mean(aloha_tmp.collision_rate_list))
    #     aloha_list.idle_rate_list.append(np.mean(aloha_tmp.idle_rate_list))
    #     slotted_aloha_list.success_rate_list.append(np.mean(slotted_aloha_tmp.success_rate_list))
    #     slotted_aloha_list.collision_rate_list.append(np.mean(slotted_aloha_tmp.collision_rate_list))
    #     slotted_aloha_list.idle_rate_list.append(np.mean(slotted_aloha_tmp.idle_rate_list))
    #     csma_list.success_rate_list.append(np.mean(csma_tmp.success_rate_list))
    #     csma_list.collision_rate_list.append(np.mean(csma_tmp.collision_rate_list))
    #     csma_list.idle_rate_list.append(np.mean(csma_tmp.idle_rate_list))
    #     csma_cd_list.success_rate_list.append(np.mean(csma_cd_tmp.success_rate_list))
    #     csma_cd_list.collision_rate_list.append(np.mean(csma_cd_tmp.collision_rate_list))
    #     csma_cd_list.idle_rate_list.append(np.mean(csma_cd_tmp.idle_rate_list))

    # plt.xlabel('Host num')
    # plt.ylabel('Success Rate')
    # plt.plot(range(1,11),aloha_list.success_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(range(1,11),slotted_aloha_list.success_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(range(1,11),csma_list.success_rate_list,marker = '*',label = 'csma')
    # plt.plot(range(1,11),csma_cd_list.success_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # plt.xlabel('Host num')
    # plt.ylabel('Idle Rate')
    # plt.plot(range(1,11),aloha_list.idle_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(range(1,11),slotted_aloha_list.idle_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(range(1,11),csma_list.idle_rate_list,marker = '*',label = 'csma')
    # plt.plot(range(1,11),csma_cd_list.idle_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # plt.xlabel('Host num')
    # plt.ylabel('Collision Rate')
    # plt.plot(range(1,11),aloha_list.collision_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(range(1,11),slotted_aloha_list.collision_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(range(1,11),csma_list.collision_rate_list,marker = '*',label = 'csma')
    # plt.plot(range(1,11),csma_cd_list.collision_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # Q7

    # aloha_list = every_rate()
    # slotted_aloha_list = every_rate()
    # csma_list = every_rate()
    # csma_cd_list = every_rate()
    # for p in range(1,20):
    #     aloha_tmp = every_rate()
    #     slotted_aloha_tmp = every_rate()
    #     csma_tmp = every_rate()
    #     csma_cd_tmp = every_rate()
    #     for i in range(30):
    #         sets = Setting(packet_size=p)
    #         success_rate, idle_rate, collision_rate = aloha(sets)
    #         aloha_tmp.success_rate_list.append(success_rate)
    #         aloha_tmp.idle_rate_list.append(idle_rate)
    #         aloha_tmp.collision_rate_list.append(collision_rate)
    #         success_rate, idle_rate, collision_rate = slotted_aloha(sets)
    #         slotted_aloha_tmp.success_rate_list.append(success_rate)
    #         slotted_aloha_tmp.idle_rate_list.append(idle_rate)
    #         slotted_aloha_tmp.collision_rate_list.append(collision_rate)
    #         success_rate, idle_rate, collision_rate = csma(sets)
    #         csma_tmp.success_rate_list.append(success_rate)
    #         csma_tmp.idle_rate_list.append(idle_rate)
    #         csma_tmp.collision_rate_list.append(collision_rate)
    #         success_rate, idle_rate, collision_rate = csma_cd(sets)
    #         csma_cd_tmp.success_rate_list.append(success_rate)
    #         csma_cd_tmp.idle_rate_list.append(idle_rate)
    #         csma_cd_tmp.collision_rate_list.append(collision_rate)

    #     aloha_list.success_rate_list.append(np.mean(aloha_tmp.success_rate_list))
    #     aloha_list.collision_rate_list.append(np.mean(aloha_tmp.collision_rate_list))
    #     aloha_list.idle_rate_list.append(np.mean(aloha_tmp.idle_rate_list))
    #     slotted_aloha_list.success_rate_list.append(np.mean(slotted_aloha_tmp.success_rate_list))
    #     slotted_aloha_list.collision_rate_list.append(np.mean(slotted_aloha_tmp.collision_rate_list))
    #     slotted_aloha_list.idle_rate_list.append(np.mean(slotted_aloha_tmp.idle_rate_list))
    #     csma_list.success_rate_list.append(np.mean(csma_tmp.success_rate_list))
    #     csma_list.collision_rate_list.append(np.mean(csma_tmp.collision_rate_list))
    #     csma_list.idle_rate_list.append(np.mean(csma_tmp.idle_rate_list))
    #     csma_cd_list.success_rate_list.append(np.mean(csma_cd_tmp.success_rate_list))
    #     csma_cd_list.collision_rate_list.append(np.mean(csma_cd_tmp.collision_rate_list))
    #     csma_cd_list.idle_rate_list.append(np.mean(csma_cd_tmp.idle_rate_list))

    # plt.xlabel('Packet size')
    # plt.ylabel('Success Rate')
    # plt.plot(range(1,20),aloha_list.success_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(range(1,20),slotted_aloha_list.success_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(range(1,20),csma_list.success_rate_list,marker = '*',label = 'csma')
    # plt.plot(range(1,20),csma_cd_list.success_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # plt.xlabel('Packet size')
    # plt.ylabel('Idle Rate')
    # plt.plot(range(1,20),aloha_list.idle_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(range(1,20),slotted_aloha_list.idle_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(range(1,20),csma_list.idle_rate_list,marker = '*',label = 'csma')
    # plt.plot(range(1,20),csma_cd_list.idle_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # plt.xlabel('Packet size')
    # plt.ylabel('Collision Rate')
    # plt.plot(range(1,20),aloha_list.collision_rate_list,marker = 'o',label = 'aloha')
    # plt.plot(range(1,20),slotted_aloha_list.collision_rate_list,marker = 'v',label = 'slotted_aloha')
    # plt.plot(range(1,20),csma_list.collision_rate_list,marker = '*',label = 'csma')
    # plt.plot(range(1,20),csma_cd_list.collision_rate_list,marker = 's',label = 'csma_cd')
    # plt.legend(loc = 'best')
    # plt.show()

    # Q8
    link_delay_list = [0,1,2,3]
    packet_size_list = [7,5,3,1]
    csma_list = every_rate()
    csma_cd_list = every_rate()
    for l,p in zip(link_delay_list, packet_size_list):
        csma_tmp = every_rate()
        csma_cd_tmp = every_rate()
        for i in range(30):
            sets =  Setting(link_delay=l, packet_size=p)

            success_rate, idle_rate, collision_rate = csma(sets)
            csma_tmp.success_rate_list.append(success_rate)
            csma_tmp.idle_rate_list.append(idle_rate)
            csma_tmp.collision_rate_list.append(collision_rate)

            success_rate, idle_rate, collision_rate = csma_cd(sets)
            csma_cd_tmp.success_rate_list.append(success_rate)
            csma_cd_tmp.idle_rate_list.append(idle_rate)
            csma_cd_tmp.collision_rate_list.append(collision_rate)

        csma_list.success_rate_list.append(np.mean(csma_tmp.success_rate_list))
        csma_list.collision_rate_list.append(np.mean(csma_tmp.collision_rate_list))
        csma_list.idle_rate_list.append(np.mean(csma_tmp.idle_rate_list))
        csma_cd_list.success_rate_list.append(np.mean(csma_cd_tmp.success_rate_list))
        csma_cd_list.collision_rate_list.append(np.mean(csma_cd_tmp.collision_rate_list))
        csma_cd_list.idle_rate_list.append(np.mean(csma_cd_tmp.idle_rate_list))



    plt.xlabel('Link delay')
    plt.ylabel('Success Rate')
    plt.plot(link_delay_list,csma_list.success_rate_list,marker = '*',label = 'csma')
    plt.plot(link_delay_list,csma_cd_list.success_rate_list,marker = 's',label = 'csma_cd')
    plt.legend(loc = 'best')
    plt.show()

    plt.xlabel('Link delay')
    plt.ylabel('Idle Rate')
    plt.plot(link_delay_list,csma_list.idle_rate_list,marker = '*',label = 'csma')
    plt.plot(link_delay_list,csma_cd_list.idle_rate_list,marker = 's',label = 'csma_cd')
    plt.legend(loc = 'best')
    plt.show()

    plt.xlabel('Link delay')
    plt.ylabel('Collision Rate')
    plt.plot(link_delay_list,csma_list.collision_rate_list,marker = '*',label = 'csma')
    plt.plot(link_delay_list,csma_cd_list.collision_rate_list,marker = 's',label = 'csma_cd')
    plt.legend(loc = 'best')
    plt.show()





if __name__=='__main__':
    main()
